title = "SAGIN 0115"
author = "Hans Hofner"

[global]
    link-foundation = 'distance'
    packet-size = 250  # 125 MBytes -> 1000 Megabits
    minutes = 1
    [global.link-foundation-params]
        distance-threshold = 'none'  # This tells whether a link is valid or not by distance.
[nodes]
    [nodes.src-nodes]
        type = 0
        count = 30
        position = 'random'
        movement = 'none'
        # Defines direct connections
        connected-to = ['base-stations', 'uav-base-stations', 'dest-nodes']
        [nodes.src-nodes.params]
            buffer-size =  0
            uplink-bandwidth = 'none'
            downlink-bandwidth = 5_000_000  # 5Kbps
            generation-rate = 1_000 # 1MBps
    [nodes.base-stations]
        type = 1
        count = 10
        position = 'none'
        movement = 'none'
        connected-to = ['src-nodes', 'base-stations', 'uav-base-stations', 'dest-nodes']
        [nodes.base-stations.params]
            buffer-size = 100_000_000 # megabytes
            uplink-bandwidth = 'none'
            downlink-bandwidth = 100_000_000 # MegaBytes per second
            generation-rate = 'none'
    [nodes.uav-base-stations]
        type = 1
        count = 10
        position = 'none'
        movement = 'none'
        connected-to = ['src-nodes', 'base-stations', 'uav-base-stations', 'dest-nodes']
        [nodes.uav-base-stations.params]
            buffer-size = 80_000_000  # MegaBytes
            uplink-bandwidth = 'none'
            downlink-bandwidth = 5_000
            generation-rate = 'none'
    [nodes.dest-nodes]
        type = 2
        count = 1
        position = 'none'
        movement = 'none'
        connected-to = ['base-stations', 'uav-base-stations']
        [nodes.dest-nodes.params]
            buffer-size = 80_000_000
            uplink-bandwidth = 'none'
            downlink-bandwidth = 5_000
            generation-rate = 'none'
[area]
    width = 10
    height = 10
